import * as THREE from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
const host=document.querySelector('#webgl-stage');
const shouldUseFallback =
  window.matchMedia('(prefers-reduced-motion: reduce)').matches ||
  window.matchMedia('(max-width: 800px)').matches;

if (shouldUseFallback) {
  document.documentElement.classList.add('no-webgl');
} else {
try {
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x020914,.042);const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,100);camera.position.set(0,0,12);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;host.appendChild(renderer.domElement);document.documentElement.classList.add('webgl-ready');const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),1.15,.55,.38));
const world=new THREE.Group();world.position.x=2.35;scene.add(world);const cloth=new THREE.MeshPhysicalMaterial({color:0x123f63,metalness:.18,roughness:.42,clearcoat:.75,clearcoatRoughness:.24,emissive:0x061a2b,emissiveIntensity:.8,side:THREE.DoubleSide}),seam=new THREE.MeshBasicMaterial({color:0x56bfff,wireframe:true,transparent:true,opacity:.22});
function panelShape(){const s=new THREE.Shape();s.moveTo(-1.42,1.62);s.quadraticCurveTo(-.85,1.9,-.5,1.72);s.lineTo(-.28,1.35);s.lineTo(.28,1.35);s.lineTo(.5,1.72);s.quadraticCurveTo(.85,1.9,1.42,1.62);s.lineTo(1.08,.75);s.lineTo(.9,-1.75);s.quadraticCurveTo(0,-2.05,-.9,-1.75);s.lineTo(-1.08,.75);s.closePath();return s}const bodyGeo=new THREE.ExtrudeGeometry(panelShape(),{depth:.42,bevelEnabled:true,bevelSize:.1,bevelThickness:.1,bevelSegments:4});bodyGeo.center();const body=new THREE.Mesh(bodyGeo,cloth);body.rotation.y=-.14;world.add(body);const bodyWire=new THREE.Mesh(bodyGeo,seam);bodyWire.scale.setScalar(1.012);bodyWire.rotation.copy(body.rotation);world.add(bodyWire);
function sleeve(side){const g=new THREE.CapsuleGeometry(.46,2.05,10,20),m=new THREE.Mesh(g,cloth);m.position.set(side*1.55,.35,.02);m.rotation.z=side*.54;m.rotation.x=.08;world.add(m);const w=new THREE.Mesh(g,seam);w.position.copy(m.position);w.rotation.copy(m.rotation);w.scale.setScalar(1.015);world.add(w)}sleeve(-1);sleeve(1);const collar=new THREE.Mesh(new THREE.TorusGeometry(.46,.08,14,70,Math.PI*1.85),new THREE.MeshStandardMaterial({color:0xff6a00,emissive:0xff6a00,emissiveIntensity:1.1,metalness:.5,roughness:.25}));collar.position.set(0,1.5,.15);collar.rotation.set(-1.45,0,0);world.add(collar);
for(let y=-1.25;y<1.35;y+=.38){const l=new THREE.Mesh(new THREE.BoxGeometry(1.76,.008,.012),new THREE.MeshBasicMaterial({color:0x4ca8df,transparent:true,opacity:.16}));l.position.set(0,y,.34);world.add(l)}const threadGroup=new THREE.Group();world.add(threadGroup);for(let i=0;i<8;i++){const a=i/8*Math.PI*2,pts=[];for(let j=0;j<90;j++){const u=j/89,rad=2.15-.25*Math.sin(u*Math.PI);pts.push(new THREE.Vector3(Math.cos(a+u*6.5)*rad,(-3.2+u*6.4)+Math.sin(a*2)*.3,Math.sin(a+u*6.5)*rad*.52))}threadGroup.add(new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts),100,i%4===0?.015:.006,5,false),new THREE.MeshBasicMaterial({color:i%4===0?0xff6a00:0x4b9dcc,transparent:true,opacity:i%4===0?.62:.18})))}
const logoTex=new THREE.TextureLoader().load('assets/techloom-logo-light.png');logoTex.colorSpace=THREE.SRGBColorSpace;const portal=new THREE.Group();portal.position.set(-3.1,1.65,-2);const portalRing=new THREE.Mesh(new THREE.TorusGeometry(1.05,.025,12,100),new THREE.MeshBasicMaterial({color:0xff6a00}));portal.add(portalRing);portal.add(new THREE.Mesh(new THREE.PlaneGeometry(1.35,.55),new THREE.MeshBasicMaterial({map:logoTex,transparent:true,depthWrite:false})));world.add(portal);
const dustGeo=new THREE.BufferGeometry(),dustPos=new Float32Array(5400);for(let i=0;i<dustPos.length;i++)dustPos[i]=(Math.random()-.5)*18;dustGeo.setAttribute('position',new THREE.BufferAttribute(dustPos,3));const dust=new THREE.Points(dustGeo,new THREE.PointsMaterial({color:0x7cc8ff,size:.018,transparent:true,opacity:.55}));scene.add(dust);scene.add(new THREE.HemisphereLight(0x4f9bd0,0x02040a,2.2));const orange=new THREE.PointLight(0xff6a00,65,13);orange.position.set(4,2,5);scene.add(orange);const rim=new THREE.PointLight(0x39a9ff,80,16);rim.position.set(0,-2,5);scene.add(rim);
let mx=0,my=0,targetScroll=0,currentScroll=0;addEventListener('pointermove',e=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5});addEventListener('scroll',()=>targetScroll=Math.min(1,scrollY/innerHeight),{passive:true});const clock=new THREE.Clock();function animate(){const t=clock.getElapsedTime();currentScroll+=(targetScroll-currentScroll)*.045;world.rotation.y+=(mx*.2+Math.sin(currentScroll*.55)*.18-world.rotation.y)*.035;world.rotation.x+=(-my*.1-Math.sin(currentScroll*.35)*.05-world.rotation.x)*.035;world.position.set(2.65+Math.sin(currentScroll*.7)*.35,Math.sin(currentScroll*.55)*.25,-.4);threadGroup.rotation.y=t*.035+currentScroll*.12;portal.rotation.z=-t*.06;portalRing.scale.setScalar(1+Math.sin(t*1.5)*.018);dust.rotation.y=t*.004;camera.position.x+=(mx*.45-camera.position.x)*.03;camera.position.y+=(-my*.25-camera.position.y)*.03;camera.position.z=11.8;camera.lookAt(1.35,0,0);composer.render();requestAnimationFrame(animate)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6))});
} catch (error) {
  document.documentElement.classList.remove('webgl-ready');
  document.documentElement.classList.add('no-webgl');
  if (host) host.replaceChildren();
  console.warn('Techloom 3D hero unavailable; static fallback active.', error);
}
}
