import * as THREE from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
const host=document.querySelector('#webgl-stage');
const shouldUseFallback =
  window.matchMedia('(prefers-reduced-motion: reduce)').matches ||
  window.matchMedia('(max-width: 800px)').matches;

if (shouldUseFallback) {
  document.documentElement.classList.add('no-webgl');
} else {
try {
const scene=new THREE.Scene();scene.fog=new THREE.FogExp2(0x020914,.042);const camera=new THREE.PerspectiveCamera(42,innerWidth/innerHeight,.1,100);camera.position.set(0,0,12);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:'high-performance'});renderer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;host.appendChild(renderer.domElement);document.documentElement.classList.add('webgl-ready');const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),1.15,.55,.38));
const world=new THREE.Group();world.position.x=2.35;scene.add(world);const cloth=new THREE.MeshPhysicalMaterial({color:0x123f63,metalness:.18,roughness:.42,clearcoat:.75,clearcoatRoughness:.24,emissive:0x061a2b,emissiveIntensity:.8,side:THREE.DoubleSide}),seam=new THREE.MeshBasicMaterial({color:0x56bfff,wireframe:true,transparent:true,opacity:.22});
function panelShape(){const s=new THREE.Shape();s.moveTo(-1.42,1.62);s.quadraticCurveTo(-.85,1.9,-.5,1.72);s.lineTo(-.28,1.35);s.lineTo(.28,1.35);s.lineTo(.5,1.72);s.quadraticCurveTo(.85,1.9,1.42,1.62);s.lineTo(1.08,.75);s.lineTo(.9,-1.75);s.quadraticCurveTo(0,-2.05,-.9,-1.75);s.lineTo(-1.08,.75);s.closePath();return s}const bodyGeo=new THREE.ExtrudeGeometry(panelShape(),{depth:.42,bevelEnabled:true,bevelSize:.1,bevelThickness:.1,bevelSegments:4});bodyGeo.center();const body=new THREE.Mesh(bodyGeo,cloth);body.rotation.y=-.14;world.add(body);const bodyWire=new THREE.Mesh(bodyGeo,seam);bodyWire.scale.setScalar(1.012);bodyWire.rotation.copy(body.rotation);world.add(bodyWire);
function sleeve(side){const g=new THREE.CapsuleGeometry(.46,2.05,10,20),m=new THREE.Mesh(g,cloth);m.position.set(side*1.55,.35,.02);m.rotation.z=side*.54;m.rotation.x=.08;world.add(m);const w=new THREE.Mesh(g,seam);w.position.copy(m.position);w.rotation.copy(m.rotation);w.scale.setScalar(1.015);world.add(w)}sleeve(-1);sleeve(1);const collar=new THREE.Mesh(new THREE.TorusGeometry(.46,.08,14,70,Math.PI*1.85),new THREE.MeshStandardMaterial({color:0xff6a00,emissive:0xff6a00,emissiveIntensity:1.1,metalness:.5,roughness:.25}));collar.position.set(0,1.5,.15);collar.rotation.set(-1.45,0,0);world.add(collar);
for(let y=-1.25;y<1.35;y+=.38){const l=new THREE.Mesh(new THREE.BoxGeometry(1.76,.008,.012),new THREE.MeshBasicMaterial({color:0x4ca8df,transparent:true,opacity:.16}));l.position.set(0,y,.34);world.add(l)}const threadGroup=new THREE.Group();world.add(threadGroup);for(let i=0;i<15;i++){const a=i/15*Math.PI*2,pts=[];for(let j=0;j<90;j++){const u=j/89,rad=2.3-.3*Math.sin(u*Math.PI);pts.push(new THREE.Vector3(Math.cos(a+u*7.5)*rad,(-3.5+u*7)+Math.sin(a*2)*.35,Math.sin(a+u*7.5)*rad*.6))}threadGroup.add(new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(pts),100,i%4===0?.018:.007,5,false),new THREE.MeshBasicMaterial({color:i%4===0?0xff6a00:0x4b9dcc,transparent:true,opacity:i%4===0?.78:.28})))}
function card(title,lines,x,y,z,rot){const c=document.createElement('canvas');c.width=720;c.height=420;const q=c.getContext('2d');q.fillStyle='#07182a';q.fillRect(0,0,720,420);q.strokeStyle='#2d5c7d';q.lineWidth=3;q.strokeRect(2,2,716,416);q.fillStyle='#ff6a00';q.fillRect(42,42,8,70);q.fillStyle='#8ca5b9';q.font='24px Arial';q.fillText('TECHLOOM / SPECIFICATION',76,62);q.fillStyle='white';q.font='bold 48px Arial';q.fillText(title,76,128);q.font='25px Arial';lines.forEach((v,i)=>{q.fillStyle=i===0?'#6fc9ff':'#91a5b6';q.fillText(v,76,205+i*48)});const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const m=new THREE.Mesh(new THREE.PlaneGeometry(2.6,1.52),new THREE.MeshBasicMaterial({map:tex,transparent:true,opacity:.92,side:THREE.DoubleSide}));m.position.set(x,y,z);m.rotation.y=rot;world.add(m);return m}const cards=[card('MATERIALS',['Nylon shell  •  120 gsm','Source-linked / proposed'],3.25,1.65,-1.5,-.5),card('CONSTRUCTION',['Seam map  •  Revision 04','Technical review required'],3.45,-1.3,.1,-.65),card('MEASUREMENTS',['18 points  •  ± 3 mm','Controlled export candidate'],-3.1,-1.55,-1.4,.52)];
const logoTex=new THREE.TextureLoader().load('assets/techloom-logo-light.png');logoTex.colorSpace=THREE.SRGBColorSpace;const portal=new THREE.Group();portal.position.set(-3.1,1.65,-2);const portalRing=new THREE.Mesh(new THREE.TorusGeometry(1.05,.025,12,100),new THREE.MeshBasicMaterial({color:0xff6a00}));portal.add(portalRing);portal.add(new THREE.Mesh(new THREE.PlaneGeometry(1.35,.55),new THREE.MeshBasicMaterial({map:logoTex,transparent:true,depthWrite:false})));world.add(portal);
const dustGeo=new THREE.BufferGeometry(),dustPos=new Float32Array(5400);for(let i=0;i<dustPos.length;i++)dustPos[i]=(Math.random()-.5)*18;dustGeo.setAttribute('position',new THREE.BufferAttribute(dustPos,3));const dust=new THREE.Points(dustGeo,new THREE.PointsMaterial({color:0x7cc8ff,size:.018,transparent:true,opacity:.55}));scene.add(dust);scene.add(new THREE.HemisphereLight(0x4f9bd0,0x02040a,2.2));const orange=new THREE.PointLight(0xff6a00,65,13);orange.position.set(4,2,5);scene.add(orange);const rim=new THREE.PointLight(0x39a9ff,80,16);rim.position.set(0,-2,5);scene.add(rim);
let mx=0,my=0,targetScroll=0,currentScroll=0;addEventListener('pointermove',e=>{mx=e.clientX/innerWidth-.5;my=e.clientY/innerHeight-.5});addEventListener('scroll',()=>targetScroll=scrollY/innerHeight,{passive:true});const clock=new THREE.Clock();function animate(){const t=clock.getElapsedTime();currentScroll+=(targetScroll-currentScroll)*.045;const chapter=currentScroll%4;world.rotation.y+=(mx*.34+Math.sin(currentScroll*.72)*.5-world.rotation.y)*.04;world.rotation.x+=(-my*.16-Math.sin(currentScroll*.4)*.1-world.rotation.x)*.04;world.position.set(2.35+Math.sin(currentScroll*.9)*1.25,Math.sin(currentScroll*.65)*1.1,-1.2+Math.cos(currentScroll*.75)*2.2);threadGroup.rotation.y=t*.08+currentScroll*.25;portal.rotation.z=-t*.12;portalRing.scale.setScalar(1+Math.sin(t*2)*.035);cards.forEach((c,i)=>{c.position.y+=Math.sin(t*.8+i)*.0009;c.material.opacity=.72+Math.sin(t+i)*.16});dust.rotation.y=t*.008+currentScroll*.035;camera.position.x+=(mx*.9+Math.sin(currentScroll*.38)*1.1-camera.position.x)*.035;camera.position.y+=(-my*.5+Math.cos(currentScroll*.47)*.5-camera.position.y)*.035;camera.position.z=11.5-Math.sin(chapter*.7)*2.4;camera.lookAt(1.2+Math.sin(currentScroll*.5),Math.sin(currentScroll*.3)*.4,0);composer.render();requestAnimationFrame(animate)}animate();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);renderer.setPixelRatio(Math.min(devicePixelRatio,1.6))});
} catch (error) {
  document.documentElement.classList.remove('webgl-ready');
  document.documentElement.classList.add('no-webgl');
  if (host) host.replaceChildren();
  console.warn('Techloom 3D hero unavailable; static fallback active.', error);
}
}
